# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e124357df3e4b1c353d3979f4987bd21ec6d4ca37eae4adb334436a3f7b809e458d803bdb9f4f0c1c7b3f7e59e2fbd026f6f672efb378dac76a75bc3c4c3dba4

test:
  secret_key_base: 697e2174e5fd2954fab576db21c72906ba4140f08a9821be43d130ac70c7479ca24225549421759c1b689540599f945bb5f0bfe2d7ec7239ff9bfed9ccc68d74

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
